# Generated by Django 5.2.13 on 2026-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_enforcer', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('self', 'Self'), ('fixed', 'Fixed'), ('hybrid', 'Hybrid')], default='hybrid', max_length=16)),
                ('enforce_student_group_conflicts', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
