# Generated by Django 5.2.13 on 2026-04-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day', 'start_time', 'end_time'], name='schedule_sc_day_58a8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher', 'day', 'start_time'], name='schedule_sc_teacher_0420df_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room', 'day', 'start_time'], name='schedule_sc_room_f7c348_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['course', 'day', 'start_time'], name='schedule_sc_course__37e24b_idx'),
        ),
    ]
